# Introduction to Open Data Science

After fiddling with my cloned repo on a suitable VPS for a while I noticed that the specs weren't really up to running R (or actually even X), so I had to revert to working on the repository on a university computer. 

All fun and games, the computer had R already installed and I requested Git from the software agent. The programmes found their way swiftly to the harddrive and I booted up Git GUI for some cloning action. Unfazed by the ascetic UI of Git GUI, I entered the source and destionation for the repository, and proceeded to wait an extended amount of time before the operation produced an error message for being unable to reach the source repo. It was time to turn to Git Bash, where a similar error reared its ugly head in the shortest of times. Not wanting to give up and install all the software on my poor Late-2010 MacBook Air (with a 64GB SSD and less RAM than the current laptops have on their GPUs), I checked the version of the Git programmes and found that they were of the crisp and modern 1.9.5 release from 2014.

After a quick support ticket to the IT helpdesk team I decided to connected to my uni network drive with the MBAir, clone via shell and then use R on the university computer. Whaddaya know, the university vPN client had started acting up and didn't restart properly, but rather needed to be killed manually. At this point the operation, which would, under normal circumstances, be a leisurely 10 minute stroll in the park, had taken about 1,5 hours with some intermittent DataCamp exercise (you know, it's the R part I'm worried about, not Git) to get some quick fixes of success. After some kill(1)ing and starting, I managed to connect to my home directory. Lo and behold, there's no Git on my MBAir - a detail that had escaped my mind completely, as I had somehow equated my trusty travel companion with my even older MacBook. Hence, while the computer holding the small piece of necessary software was sturdily on my desk back home, I resorted to accepting the kind offer from OS X to install "command line tools". After the five-or-so-minute installation and another five banging my head to the proverbial wall with typing "oids" instead of "iods" and wondering why the clone won't work, I had the repo cloned to my university home directory.

After this ordeal, working with DataCamp was easy and the assignments were a breeze. Or so I thought while I was completing the generic "Introduction to R" assignments, but not the course-specific assignments that I discovered later.

My Github repo is [here](https://github.com/fanders-iods/IODS-project).